version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/deployment
permissions:
  - object: /home/ec2-user/deployment/
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - chmod +x scripts/deploy.sh
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
